Add .gitignore file
Diacrome/super-scoring pull request #11
Opened 2022-04-26 08:53 UTC by Lilongue

2022-04-26 08:55 UTC, Lilongue commented
Add .gitignore file

2022-04-27 14:57 UTC, Diacrome commented on .gitignore
> +
последняя строка должна быть пустой

2022-04-27 14:57 UTC, Diacrome commented on .gitignore
> +
последняя строка должна быть пустой

2022-04-27 14:58 UTC, Diacrome requested changes
последняя строка должна быть пустой

2022-04-28 10:38 UTC, Lilongue commented on .gitignore
> +
Исправил

2022-04-28 10:38 UTC, Lilongue commented on .gitignore
> +
Вроде бы исправил

2022-04-28 10:41 UTC, Diacrome approved these changes

2022-04-28 10:42 UTC, merged