Dockerfile refacror
Diacrome/super-scoring pull request #12
Opened 2022-04-26 09:09 UTC by Lilongue

Сжатие конечного Docker-образа

2022-04-26 18:19 UTC, Diacrome requested changes
ответить на вопрос
исправить пустую строку
в следующий раз следовать правилам разработки в миро

2022-04-26 18:19 UTC, Diacrome commented on backend/Dockerfile
> +FROM openjdk:11-jre-slim
просто в слим сразу собрать нельзя?

2022-04-26 18:19 UTC, Diacrome commented on .gitignore
> +
последняя строка должна быть пустой.

2022-04-27 15:43 UTC, Lilongue commented on backend/Dockerfile
> +FROM openjdk:11-jre-slim
В jre-slim - нет jdk и maven для сборки. Если их установить, то образ получиться не таким уж и slim
В первом from берется контейнер для сборки проекта, потом из него копируется только jar, остальное - не сохраняется после сборки. Jar уже пихается в slim из второго from, где только jre. Этот контейнер не содержит ничего лишнего, в том числе исходников проекта - если вдруг его придется распространять и существенно меньше весит. 
В качестве альтернативы можно предложить скрипт, который собирает проект на хосте, а дальше в одну стадию сразу в slim кладет исходник, но тут могут быть разные версии maven на хостах...

2022-04-27 15:50 UTC, Diacrome approved these changes
Не забыть засквошить и проверить работоспособность перед мерджем

2022-04-28 06:21 UTC, Diacrome approved these changes

2022-04-28 07:07 UTC, merged