SS-12 Added methods for start testing
Diacrome/super-scoring pull request #14
Opened 2022-05-02 08:34 UTC by bagmarya

2022-05-03 16:45 UTC, Diacrome requested changes
доработать по вопросам

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +@Path("/ss")
Может меня не правильно поняли, но ss ничего не значит и просто так писать не нужно
Имеет смысл сделать /test 
и продолжение ниже  
/start
/questions

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionDto.java
> +  private String wording;
wording это формулировка? 
с первого раза не понятно

предлагаю description или question или еще чего

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassRecord.java
> +  private List<Integer> questionIds = new ArrayList<Integer>();
сюда не только id в List<Integer> связать, 
а прям List<Question>

попробуй

2022-05-03 16:45 UTC, Diacrome commented on backend/init.sql
> +--    question_ids        int[]   not null,
не нужный комментарий

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +public class SSResource {
SSresource это ошибка, не должно такого быть
TestResource - надо фронтендерам сказать что ss меняем

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      rec.setQuestionIds(questionService.getQuestionsForStart(testID, 10));
10 в константу и в начало класса private static int

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +    return null;
```suggestion
    return List.of();
```
Лучше возвращать в заявленном в методе виде

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public void saveRecord(Integer testID, Integer userId) {
лучше назвать startTest

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +    return Response.status(201).build();
если тест уже есть в процессе, то лучше вернуть 400

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      TestPassRecord rec = new TestPassRecord();
не rec, а Test

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      System.out.println("Для этого пользователя уже существует запись о незавершенном тестированиии.");
System.out.println быть не должно, для этого логгер используют

2022-05-03 16:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public void saveRecord(Integer testID, Integer userId) {
почему void?
нужно возвращать Map<Integer, Question>
{questionID: question,
questionID: question
...
}

2022-05-03 17:59 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionDto.java
> +  private String wording;
problem - подойдет?

2022-05-03 17:59 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassRecord.java
> +  private List<Integer> questionIds = new ArrayList<Integer>();
Не понятно, что именно попробовать.

2022-05-03 18:03 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public void saveRecord(Integer testID, Integer userId) {
мы же разделили процесс регистрации новой записи о прохождении тестирования и процесс получения вопросов для данного прохождения на две отдельные "ручки". Так зачем же возращать словарь с вопросами при регистрации записи? Куда он дальше пойдет? не понимаю.

2022-05-03 18:07 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      TestPassRecord rec = new TestPassRecord();
страшно запутаться с бесконечным обилием "test", можно переменная будет: "testPassRecord" - с маленькой буквы, но по имени класса?

2022-05-03 18:08 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      System.out.println("Для этого пользователя уже существует запись о незавершенном тестированиии.");
Забыла стереть перед commit )

2022-05-03 18:36 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
> -    return new MappingConfig(Test.class);
ок

2022-05-03 18:36 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/entity/Question.java
> +
ок

2022-05-03 18:36 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +@Path("/ss")
ок

2022-05-03 18:36 UTC, bagmarya commented on backend/init.sql
> +--    question_ids        int[]   not null,
ок

2022-05-03 18:37 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +public class SSResource {
ок

2022-05-03 18:37 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      rec.setQuestionIds(questionService.getQuestionsForStart(testID, 10));
ок

2022-05-03 18:37 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +    return null;
ок

2022-05-03 18:37 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +    return Response.status(201).build();
ок

2022-05-03 18:38 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      TestPassRecord rec = new TestPassRecord();
да testPassRecord нормально.
Record - не несёт в себе дополнительного смысла, хорошо бы вообще класс назывался TestPass

2022-05-03 18:42 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionDto.java
> +  private String wording;
Потому что question это весь объект в целом. Но можно сделать и question, ok.

2022-05-03 18:44 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      TestPassRecord rec = new TestPassRecord();
ок

2022-05-03 18:45 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      TestPassRecord rec = new TestPassRecord();
но тогда и таблицу в скл лучше переименовать?

2022-05-03 18:57 UTC, Diacrome reviewed
ответил

2022-05-03 18:57 UTC, Diacrome commented on backend/README.md
> +`POST /ss/start/{test_id}`
в java принят camelCase -> testId

2022-05-03 18:57 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +  @Path("/start/{test_id}")
в java принят camelCase -> testId

2022-05-03 18:57 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassRecord.java
> +  private List<Integer> questionIds = new ArrayList<Integer>();
List\<Question> 
форматирование съело.
тогда при запросе вопросов можно возвращать map c id вопросов и самим вопросом

2022-05-03 18:57 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +      TestPassRecord rec = new TestPassRecord();
да

2022-05-03 18:57 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public void saveRecord(Integer testID, Integer userId) {
ок, с разъяснением понятно

2022-05-03 18:57 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public void saveRecord(Integer testID, Integer userId) {
map нужно возвращать на запрос с question

2022-05-07 13:41 UTC, Diacrome requested changes
порешать конфиликты

2022-05-08 16:30 UTC, Diacrome requested changes
добавить пример

2022-05-08 16:30 UTC, Diacrome commented on backend/README.md
> +* **payload** - варианты ответа (в виде: {"1":"первый вариант ответа","2":"второй вариант ответа"}})
пример в формате json
```
{
    "id": 1,
    "name": "Математический тест",
    "description": "Решите 10 математичесчких задач.",
}
```

2022-05-08 17:40 UTC, Diacrome approved these changes

2022-05-09 04:23 UTC, merged