Getting information about the test to be taken
Diacrome/super-scoring pull request #15
Opened 2022-05-03 09:38 UTC by newvasuki-newvasuki

Getting information about the test to be taken

2022-05-03 15:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  public Response getTestObject(@PathParam("id") String id) {
Почему id String а не int?
И валидатор встроенный тогда используется, дополнительно дописывать ничего не надо

2022-05-03 15:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
> -  public Response getTestObject(@PathParam("id") String id) throws JsonProcessingException {
а вот откуда String id.
Да, надо внимательнее смотреть

2022-05-03 15:43 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
> -  public String hello() {
Хочется оставить ручку для тестирования работоспособности приложения. После поднятия приложения нужно проверить что работает.

2022-05-03 16:07 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @Path("ss/start/{id}")
в miro так было, поменяю

2022-05-03 16:08 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/dao/GenericDao.java
> -
ок

2022-05-03 16:08 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
> -  public Response getTestObject(@PathParam("id") String id) throws JsonProcessingException {
я осмысленно String оставил

2022-05-03 16:09 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  public Optional<Test> getTestById(String id) {
хорошо

2022-05-03 16:09 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
> -  public String hello() {
хорошо

2022-05-03 16:17 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  public Response getTestObject(@PathParam("id") String id) {
стандартизация это хорошо

2022-05-03 16:18 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @Path("ss/start/{id}")
проверю в миро, не ты один такую ошибку делашь

2022-05-03 19:13 UTC, Diacrome requested changes
пройтись по пунктам

2022-05-03 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  public Optional<Test> getTestById(Integer id) {
зачем optional?
null это ок

дополнительная обвязка которая используется только для проверки обвязки.
Про чистого кота - там вроде дело в контесксте было, я уже не помню что там.
null можно использовать

2022-05-03 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @POST
get, вон ниже getTestObject

2022-05-03 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +@Path("/")
/test

2022-05-03 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @Path("start/{id}")
info/{id}

2022-05-03 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/HelloResource.java
> +  @GET
добавь путь /hello пожалуйста.
на корне отдавать не очень.

и в readme

2022-05-03 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Test.java
> -@Table(name = "test")
пожалуйста попробуй, ещё раз с аннотацией.

2022-05-04 04:11 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  public Response getTestObject(@PathParam("id") Integer id) {
ок

2022-05-04 04:12 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  public Optional<Test> getTestById(Integer id) {
ок

2022-05-04 04:15 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @POST
ок

2022-05-04 04:15 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +@Path("/")
ок

2022-05-04 04:15 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @Path("start/{id}")
ок

2022-05-04 04:15 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/HelloResource.java
> +  @GET
ок

2022-05-04 10:14 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @POST
POST из miro идёт, я картинку присылал

2022-05-04 10:57 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +    if (test != null) {
2 раза одно и тоже проверяешь и в сервисе и в ресурсе.
Можно остравить только в ресурсе и лог туда перенести если очень хочется. или просто удалить

2022-05-04 11:20 UTC, Diacrome requested changes
проект не компилируется, поправить классы с настройками

2022-05-04 11:20 UTC, Diacrome commented on backend/README.md
> +Возвращает JSON объект с полями:
пример json объекта предоставь пожалуйста

2022-05-04 11:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Test.java
> +  public void setModifierId(Integer modifierId) {
сеттеры можно не генерировать, если они не используются.
лучше убрать.

2022-05-04 11:35 UTC, Diacrome requested changes
замечание + не компилируется проект

2022-05-04 11:35 UTC, Diacrome commented on backend/README.md
> +    "modifierId": null
Плохая идея отдавать внутренние id просто так. Фронту от них ни жарко ни холодно, + раскрытие внутренностей без надобности. Возвращать надо имя и фамилию, или вообще ничего. Для этого нужно сделать класс ДТО.

2022-05-04 13:21 UTC, Diacrome requested changes
небольшие замечания

2022-05-04 13:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Test.java
> +    return dateCreated.toString();
не нужно преобразовывать без нужды

2022-05-04 13:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Test.java
> +    return dateModified != null ? dateModified.toString() : "not modified yet";
не нужно преобразовывать без нужды

2022-05-04 13:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  private TestDto convertTestToTestDto(Test test) {
метод относится к классу дто, там ему и место.
можно сделать статический метод 
```
TestDto map(Test test) {
...
}
```

2022-05-04 14:28 UTC, Diacrome approved these changes
1 замтка по кодстайлу

2022-05-05 07:43 UTC, merged