SS-13 Recording the answer
Diacrome/super-scoring pull request #16
Opened 2022-05-05 10:00 UTC by Lilongue

2022-05-09 08:44 UTC, Diacrome requested changes
сделать ребейз на мастер
продолжить работу.

по поводу полей и их содержимого договориться с Артемом и Марией

2022-05-09 08:44 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Answer.java
> +@Table(name = "Answers")
по правилам таблицы именнуют в единственном числе - answer

2022-05-09 08:44 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Answer.java
> +  private Timestamp timeAnswer;
LocalDateTime

2022-05-09 08:44 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Answer.java
> +  @Column(name = "time_took")
Мы же договорились записывать время ответа, а не сколько это заняло времени.Пояни как работают поля времени

2022-05-09 08:44 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +  public Response saveAnswer(@FormParam("questionId") String questionString,
```suggestion
  public Response saveAnswer(@FormParam("questionId") int questionId,
```

2022-05-09 08:44 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    Integer testPassRecordId = answerDao.getRecordByUserId(userId).get(); // тут, возможно, надо проверить на пустоту
надо проверить на пустоту.
если нет текущего теста, возващать ошибку

2022-05-09 08:44 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    answer.setQuestion(questionId);             // тут, возможно, надо проверить на наличие такого id
нам нужно записывать не глобальный questionId, а номер вопроса в данном тесте. от 1 до 10

2022-05-09 13:27 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/entity/Answer.java
> +  @Column(name = "time_took")
Я тоже понял из обсуждения, что записываем время ответа, но когда готовили базу в изначальный вариант попало поле int со временем , затраченным на ответ. Я его тоже считаю лишним, но оставил пока (на случай если понял неправильно). Уберу.

2022-05-09 13:29 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +  public Response saveAnswer(@FormParam("questionId") String questionString,
Ок.

2022-05-09 13:29 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    Integer testPassRecordId = answerDao.getRecordByUserId(userId).get(); // тут, возможно, надо проверить на пустоту
Ок. Сделаю

2022-05-09 13:38 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    answer.setQuestion(questionId);             // тут, возможно, надо проверить на наличие такого id
Ок. Поменяю на номер в тесте. Меня смутила запись на доске: там id вопроса передается. Нужно будет фронт предупредить, что другой концепт.

2022-05-12 18:45 UTC, Diacrome requested changes
по комментариями

2022-05-12 18:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
> +    //GenericDao.class,
коммент убрать

2022-05-12 18:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +import java.time.LocalDateTime;
навести порядок с импортами
форматирование ctrl alt L с примененным настренным файлом

2022-05-12 18:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
> +package ru.hh.superscoring.resource;
откуда этот файл? почему он в диффе?

2022-05-12 18:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  public Integer getRecordByUserId(Integer userId) {
не record, а testPass.
по хорошему запрос нужно перенести в testpassdao, а обращаться через прослойку testpassservice
Транзакцию вешают на уровне сервиса по умолчанию

2022-05-12 18:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    if (testPassId == null){
если не находит то getsingleresult кидает ошибку NoResultException e
вроде. надо проверить а не null

2022-05-12 18:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +                             ){
форматирование и импорты

2022-05-12 18:48 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +      return Response.status(400).entity("Что-то пошло не так! " + e.toString()).build();
```suggestion
      return Response.status(400).entity("Что-то пошло не так! ").build();
```
не отдаем внутреннюю инфу внешним пользователям

2022-05-14 07:14 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
> +    //GenericDao.class,
ок

2022-05-14 07:17 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +import java.time.LocalDateTime;
Ок

2022-05-14 07:25 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/ExampleResource.java
> +package ru.hh.superscoring.resource;
Изначально он был в ветке Марии SS-6 и, соответственно, в main. Это приветствие по корню. Потом его, видимо, Кирилл выпилил, заменив приветствие на /hello. У меня остался из-за излишне бережливого отношения). Видимо, он не нужен и я его удалю.

2022-05-14 07:27 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +                             ){
Ок

2022-05-14 07:38 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +      return Response.status(400).entity("Что-то пошло не так! " + e.toString()).build();
Ок.

2022-05-14 07:44 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    if (testPassId == null){
Исправил в Dao. В случае исключения возвращает null

2022-05-14 08:15 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  public Integer getRecordByUserId(Integer userId) {
Я перенес в TestPassDao, только общаюсь без прослойки - напрямую, добавив testPassDao в AnswerService. Или так не делают?

2022-05-14 17:38 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  public Integer getRecordByUserId(Integer userId) {
нормально

2022-05-14 17:46 UTC, Diacrome requested changes
см замечания

2022-05-14 17:46 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +    //  @QueryParam(value = "testPassId") Integer testPassId // заготовка для получения userId
нужно реализовать

2022-05-14 17:46 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw (new PropertyValueException("No testPass for such user!", "AnswerDao", "userId"));
какой код запрос возвращает?
нужно 400 и сообщение о том что нет активного теста, а не что-то пошло не так.

2022-05-15 12:55 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw (new PropertyValueException("No testPass for such user!", "AnswerDao", "userId"));
Перехватил PropertyValueException на уровне сервиса и отправил осмысленную ошибку.

2022-05-15 12:56 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +    //  @QueryParam(value = "testPassId") Integer testPassId // заготовка для получения userId
предлагаю в отдельной ветке

2022-05-15 14:38 UTC, Diacrome requested changes
см комменты

2022-05-15 14:38 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +          .getSingleResult();
можно просто uniqueresult запрашивать, он null возвращает если не нашел. ошибку ловить не придется

2022-05-15 14:38 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw (new PropertyValueException("No testPass for such user!", "AnswerDao", "userId"));
а код какой?

2022-05-16 02:30 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw (new PropertyValueException("No testPass for such user!", "AnswerDao", "userId"));
Код 400. Повторно в ресурсе перехватывается ошибка.

2022-05-16 02:51 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +          .getSingleResult();
Переделал на uniqueResult

2022-05-16 19:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw (new PropertyValueException("No testPass for such user!", "AnswerDao", "userId"));
я бы на unique result заменил, зачем лишние ошибки и трай кэтчи. но сам смотри

2022-05-16 19:14 UTC, Diacrome approved these changes
по коменту на твое усмотрение

2022-05-16 22:12 UTC, merged