SS-14 Add status
Diacrome/super-scoring pull request #18
Opened 2022-05-05 21:05 UTC by Chopr39

https://trello.com/c/tYKph9A8

2022-05-07 13:45 UTC, Diacrome commented on backend/init.sql
> +       (10, 1, 15, '3', now(), 1);
пустая строка

2022-05-08 07:38 UTC, Chopr39 commented on backend/init.sql
> +       (10, 1, 15, '3', now(), 1);
настроил в идее, больше такого не должно повториться

2022-05-09 08:54 UTC, Diacrome requested changes
нужно сделать ребейз на мейн и продолжить работу с учетом новых полей

2022-05-09 08:55 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/SSResource.java
> +    int sessionId = Integer.parseInt(request.getSession().getId());
можно написать userId = 1 или посмотреть в базе, спросить у Артема или Марии

2022-05-17 20:06 UTC, Diacrome requested changes
сделать ребейз на мэйн rebase origin/main
собрать инфу из указанных методов
сформировать необходимую дто

2022-05-17 20:06 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/StatusDao.java
> +public class StatusDao extends GenericDao {
здесь тебе нужно написать метод получения ответов по всем вопросам https://github.com/Diacrome/super-scoring/blob/e8ab40a55f26413606e62227136aa08b48db1890/backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java#L5

если ответов нет - вопрос не отвечен

2022-05-17 20:06 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  @Transactional
здесь можно получить вопросы по тест id https://github.com/Diacrome/super-scoring/blob/e8ab40a55f26413606e62227136aa08b48db1890/backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java#L14

все вместе собрать

2022-05-19 20:09 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +    status.setCurrentPass(getCurrentPass(id));
убрал транзакцию, так как изменяющуюся информацию(ответы) достаю одним запросом. а время старта теста и тестId не меняются

2022-05-19 20:09 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/resource/StatusResource.java
> +//    int sessionId = Integer.parseInt(request.getSession().getId());
исправил

2022-05-19 20:10 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/resource/StatusResource.java
> +    int sessionId = 1; //temporary mock
исправил

2022-05-19 20:10 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/dao/StatusDao.java
> +public class StatusDao extends GenericDao {
сделал

2022-05-19 20:14 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  @Transactional
этот метод для получения вопросов по testId
Я добавил метод для получения вопросов по текущему прохождению

2022-05-19 20:36 UTC, Diacrome requested changes
Довести до работоспособного состояния или задавать вопросы в ПР или в личку

2022-05-19 20:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    } catch (NoResultException e) {
метод не кидает ошибку. если не найден то  null

2022-05-19 20:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    statusDto.setCurrentPass(getCurrentPass(authorized, userId));
если authorized null, дальше можно не ходить и не нагружать базу

2022-05-19 20:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +    String sqlQuery = "SELECT  new map( " +
первый раз такое вижу. Как оно работает.
Расскажи или почитай про хибер и перепиши.

Если не понятно задавай вопросы

2022-05-23 16:50 UTC, Diacrome requested changes
не выполняет заявленную логику, доработать

2022-05-23 16:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    currentPass.setTestId(testPassDao.getTestId(testPassId));
если это testPassId, то и параметр дто должен называться testPassId

2022-05-23 16:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    for (int i = 0; i < NUMBER_OF_QUESTIONS; i++) {
не понятно как ты определяешь есть ли ответ или нет.
не вуижу похода в таблицу answers

2022-05-23 19:38 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    currentPass.setTestId(testPassDao.getTestId(testPassId));
я должен получить testId. Для этого я иду в таблицу testPass через соответствующий dao и подставляю testPassId в качестве аргумента

2022-05-23 19:42 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    for (int i = 0; i < NUMBER_OF_QUESTIONS; i++) {
в таблицу answer попадают только "отвеченные ответы". Поэтому на 44 строке я забираю список порядковых номеров отвеченных вопросов из таблицы answer и далее определяю, каких ответов не хватает.

2022-05-25 18:13 UTC, Diacrome requested changes
по вопросам

2022-05-25 18:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +  @Transactional(readOnly = true)
убратьможно в сервисе на главном методе повесить аннотацию, а в дао убратьать

2022-05-25 19:32 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +  @Transactional(readOnly = true)
Сделал. Но не убрал аннотацию в методе TestPassDao.getTestPassByUserId(), потому что не мой код

2022-05-25 20:20 UTC, Chopr39 commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    }
класс!

2022-05-27 15:38 UTC, Diacrome approved these changes
ребейз, проверка и мердж

2022-05-28 10:02 UTC, merged