SS-10 Add token-based authorization, return user for token
Diacrome/super-scoring pull request #22
Opened 2022-05-08 22:06 UTC by moonb3rry

2022-05-09 08:20 UTC, Diacrome requested changes
замечания

добавить ручку получение токена. 
присылаешь @ forma param  логин и пароль - генерится токе, записывается во базу и возвращает объект
{token: 'sfdfdssfdsfbdsbfsfvsdvf'}

2022-05-09 08:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +@Qualifier("authDao")
qualifer не нужен будет после ребейза

2022-05-09 08:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +    } else {
можно без else

2022-05-09 08:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/t")
буквы не экономим, token

2022-05-09 08:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response getUserByToken(@Context HttpHeaders headers) {
аннотоация @ HeaderParam("authorization") String token

2022-05-09 08:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    String authorizationToken = headers.getRequestHeader("Authorization").get(0);
get(0) падает если не прислать заголовок
проверять что token не 0

2022-05-09 08:20 UTC, Diacrome commented on backend/init.sql
> +create table user_account
сделай ребэйз на мэйн
или использую юзера https://github.com/Diacrome/super-scoring/blob/9308ebd61dd115f0373fe5e43bd25583b9e78e44/backend/init.sql#L1
и добавь ему поле Имя

2022-05-09 08:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +  public static UserDto map(User user) {
Добавить в юзера поле name, возвращать только имя по токену

2022-05-09 11:11 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +  public static UserDto map(User user) {
login на name поменять или добавить еще одно поле?
и почему нужно возвращать имя по токену (оно уникальное)?

2022-05-09 20:09 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +  public static UserDto map(User user) {
name - новое поле, например - Екатирина. У пользователя должно быть имя.
Эта ручка - проврить что токен работает и все.

2022-05-09 20:36 UTC, moonb3rry commented
Сделать:
1. возврат имени по токену в auth/token
2. проверить-доделать /auth/login
3. readme
4. добавить рабочий expireDate

2022-05-10 12:13 UTC, Diacrome requested changes
рассмотреть замечания

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional
По хорошему транзакция открывается на уровне сервиса
транзакция только для чтени
 @Transactional(readOnly = true)

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional
только чтение

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional
только чтение

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Token.java
> +  @Column(name = "access_token")
лучше просто token

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Token.java
> +  @Column(name = "access_token")
лучше просто token

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      else
else не нужен

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      else
else не нужен

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
else не нужен

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
else не нужен

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
else не нужен

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
else не нужен

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  public void generateNewAccessToken(Integer userId, String accessToken) {
лучше использовать стандартный save

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  public void generateNewAccessToken(Integer userId, String accessToken) {
лучше использовать стандартный save

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
> +}
добавить пустую строку

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
> +}
добавить пустую строку

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +  public void generateAccessToken(Integer userId) {
нет транзации

2022-05-10 12:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +  public void generateAccessToken(Integer userId) {
нет транзации

2022-05-10 18:49 UTC, Diacrome requested changes
Оформить ПР по правилам разработки в Миро.
Отвечать на все вопросы.
Добавить в  init.sq при старте тестовый токен для какого-то юзера и сказать после релиза его фронтам для теста

2022-05-10 20:13 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response userLogin(@PathParam("login") String login, @PathParam("password") String password) {
в условиях передавать FormParam url-encoded

потом поправишь

2022-05-10 20:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +        .createQuery("select u.userId from User u where u.login = :login and u.password = :password", Integer.class)
```suggestion
        .createQuery("select u.id from User u where u.login = :login and u.password = :password", Integer.class)
```
неправильный нейминг

2022-05-10 20:32 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/entity/Token.java
> +  @Column(name = "access_token")
поменяю

2022-05-10 20:32 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional
+

2022-05-10 20:33 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +        String r = "User found : " + userName;
спасибо большое ! теперь хватит

2022-05-10 20:33 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
хорошо

2022-05-10 20:33 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      String userName = userService.getUserNameById(authService.getUserWithToken(authorizationToken));
сделаю

2022-05-10 20:34 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +    token.setExpireDate(LocalDateTime.now().plusMinutes(20));
хорошо

2022-05-10 20:35 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +        return Response.status(201, r).build();
ок

2022-05-11 12:21 UTC, Diacrome requested changes
см заметки

2022-05-11 12:21 UTC, Diacrome commented on backend/README.md
> +{"name": Anna}
кавычки анна

2022-05-11 12:21 UTC, Diacrome commented on backend/README.md
> +{"token": ktuq13qll08kmg8oc49b}
кавычки токен

2022-05-11 12:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +public class UserDto {
дто класс вообще не нужен

2022-05-11 12:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/login/")
```suggestion
  @Path("/token")
```

2022-05-11 12:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/UserService.java
> +    return userDao.getUserNameById(authService.getUserWithToken(token));
можно сделать за 1 hql запрос

2022-05-11 12:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/TokenDto.java
> +public class TokenDto {
токен дто не нужно

2022-05-11 12:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      return Response.ok(token).build();
формат ответа {"token": "dsdsdsdssd"}

2022-05-11 12:21 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/token")
/check-token

2022-05-11 12:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/token")
ок

2022-05-11 12:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      return Response.ok(token).build();
ок

2022-05-11 12:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/login/")
ок

2022-05-11 12:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dto/TokenDto.java
> +public class TokenDto {
оба дто убрала

2022-05-11 12:28 UTC, moonb3rry commented on backend/README.md
> +{"token": ktuq13qll08kmg8oc49b}
везде кавычки добавила

2022-05-11 12:31 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/UserService.java
> +    return userDao.getUserNameById(authService.getUserWithToken(token));
хорошо, но если понадобятся по токену другие данные помимо имени, которые через айди вытянуть можно?

2022-05-11 12:40 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/UserService.java
> +    return userDao.getUserNameById(authService.getUserWithToken(token));
а если не понадобятся?
тем кому понядобятся пусть потом пишут.

2022-05-11 12:41 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/UserService.java
> +    return userDao.getUserNameById(authService.getUserWithToken(token));
окей

2022-05-11 14:22 UTC, moonb3rry commented on backend/README.md
> +{"name": Anna}
ок

2022-05-11 14:22 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +public class UserDto {
ок

2022-05-11 14:25 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response userLogin(@PathParam("login") String login, @PathParam("password") String password) {
сделано

2022-05-11 14:25 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +  public void generateAccessToken(Integer userId) {
теперь естьь

2022-05-11 14:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +  public void generateAccessToken(Integer userId) {
есть

2022-05-11 14:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/config/CommonConfig.java
> +}
добавила

2022-05-11 14:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  public void generateNewAccessToken(Integer userId, String accessToken) {
ок

2022-05-11 14:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  public void generateNewAccessToken(Integer userId, String accessToken) {
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    } else {
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      else
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/entity/Token.java
> +  @Column(name = "access_token")
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional
ок

2022-05-11 14:27 UTC, moonb3rry commented on backend/init.sql
> +create table user_account
ок

2022-05-11 14:28 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +    String authorizationToken = headers.getRequestHeader("Authorization").get(0);
ок

2022-05-11 14:28 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/t")
у меня много букв

2022-05-11 14:28 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dto/UserDto.java
> +    } else {
ок

2022-05-11 14:28 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +@Qualifier("authDao")
ок

2022-05-11 14:41 UTC, Diacrome requested changes
заметки
проверить запросы с ответом 404

2022-05-11 14:41 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/token/")
```suggestion
  @Path("/token")
```

2022-05-11 14:41 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response userLogin(@FormParam("login") String login, @FormParam("password") String password) throws JsonProcessingException {
```suggestion
  public Response userLogin(@FormParam("login") String login, @FormParam("password") String password) {
```

2022-05-11 14:41 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response getUserByToken(@HeaderParam("authorization") String authorizationToken) throws JsonProcessingException {
```suggestion
  public Response getUserByToken(@HeaderParam("authorization") String authorizationToken) {
```

2022-05-11 14:41 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response userLogin(@FormParam("login") String login, @FormParam("password") String password) throws JsonProcessingException {
```suggestion
  public Response generateToken(@FormParam("login") String login, @FormParam("password") String password) throws JsonProcessingException {
```

2022-05-11 15:22 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  @Path("/token/")
исправила

2022-05-11 15:22 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +  public Response getUserByToken(@HeaderParam("authorization") String authorizationToken) throws JsonProcessingException {
ок

2022-05-12 18:23 UTC, Diacrome approved these changes
Заметки исправить, проверить и мердж

2022-05-12 18:23 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/UserService.java
> +package ru.hh.superscoring.service;
удалить файл UserService.java

2022-05-12 18:23 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional(readOnly = true)
транзакцию по умолчанию открывают в сервисе

2022-05-12 18:37 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      return Response.status(404, "Some error occurred").build();
some error - 400

2022-05-12 19:42 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      userId = authService.checkAuthentification(login, password);
ок

2022-05-12 19:43 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/UserService.java
> +package ru.hh.superscoring.service;
ок

2022-05-12 19:43 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional(readOnly = true)
сделала

2022-05-12 19:43 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/AuthDao.java
> +  @Transactional(readOnly = true)
тоже сделала

2022-05-12 19:43 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/AuthResource.java
> +      return Response.status(404, "Some error occurred").build();
ок

2022-05-12 20:12 UTC, merged