SS-25 StartTest refactoring
Diacrome/super-scoring pull request #28
Opened 2022-05-14 15:11 UTC by bagmarya

2022-05-14 18:22 UTC, Diacrome requested changes
по замечниям
+ получать user id из заголовка

2022-05-14 18:22 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassQuestion.java
> +  @JsonIgnore
а вдруг кому-то понадобиться
такие вещи разруливаются на уровне дто. тут определённо убрать

2022-05-14 18:22 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>        testPass.setTestId(testID);
```suggestion
      testPass.setTestId(testId);
```

2022-05-14 18:22 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPass.java
> +  @OneToMany(mappedBy = "testPass", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
EAGER -> lazy
cascade = CascadeType.ALL - не стоит. при удалении 1 связанног выделенного вопроса все прохождение удалится

2022-05-14 18:22 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
> +    return Response.ok(QuestionDto.QuestionsForTestDto.map(questions)).build();
QuestionDto.QuestionsForTestDto.map(questions)

выглядит страшновато.
по возможности оставить 1 название класса.map

2022-05-14 18:22 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
>          .createQuery("select r from TestPass r where r.userId = :user_id and r.timeFinished is null ", TestPass.class)
если убрать eager, то тут понадобится fetch 
это база, обязательное знание
https://habr.com/ru/company/otus/blog/529692/

2022-05-15 05:40 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/entity/TestPass.java
> +  @OneToMany(mappedBy = "testPass", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
ок

2022-05-15 05:40 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>        testPass.setTestId(testID);
ок

2022-05-15 05:41 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassQuestion.java
> +  @JsonIgnore
ok

2022-05-15 05:45 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
>  import java.util.List;
ok

2022-05-15 05:46 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>    public Boolean startTest(Integer testID, Integer userId) {
ok

2022-05-15 05:46 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>        return true;}
ok

2022-05-15 08:26 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
>          .createQuery("select r from TestPass r where r.userId = :user_id and r.timeFinished is null ", TestPass.class)
ok

2022-05-15 09:18 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassQuestion.java
> +  @ManyToOne(fetch = FetchType.EAGER)
Здесь можно EAGER оставить? Не имеет смысла запрашивать порядок вопросов без самих вопросов.

2022-05-15 13:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPassQuestion.java
> +  @ManyToOne(fetch = FetchType.EAGER)
да

2022-05-15 14:28 UTC, Diacrome requested changes
см. замечания
следовать правилам разроботки - добавить ссылку на карточку в ПР
следующие коммиты на английском языке, начинаются на SS-25

2022-05-15 14:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>    private final QuestionService questionService;
удалить

2022-05-15 14:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +
импорты поправить

2022-05-15 14:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public Set<TestPassQuestion> getUnfinishedPassQuestions(Integer userId) {
перенести сюда @Transactional(readOnly = true) из дао testPassDao.isExistUnfinishedRecord

2022-05-15 14:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
>    @Transactional(readOnly = true)
убрать @Transactional(readOnly = true)

2022-05-15 14:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +        .createQuery("select tp from TestPass tp join fetch tp.questions where tp.userId = :user_id and tp.timeFinished is null ", TestPass.class)
зачем мы TestPass выбираем если нам вопросы нужны?
можно сразу select tp.questions ?
или вообще сразу из question выбирать?

2022-05-15 14:32 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionDto.java
> +    if (q == null) {
буквы беспплатные, вот держи: question

2022-05-15 14:33 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionDto.java
> +    if (q == null) {
однобуквенные перемнные обычно не делаем

2022-05-15 14:35 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPass.java
> +  @Cascade(CascadeType.SAVE_UPDATE)
зачем какскад? Что он делает, я не понимаю. объясни

2022-05-15 14:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +        .createQuery("select tp from TestPass tp join fetch tp.questions where tp.userId = :user_id and tp.timeFinished is null ", TestPass.class)
если долго не будет получаться, можно пока оставить так

2022-05-15 17:40 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +
ok

2022-05-15 17:48 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/entity/TestPass.java
> +  @Cascade(CascadeType.SAVE_UPDATE)
При сохранении объекта TestPass сохраняются все связанные с ним объекты TestPassQuestion , которые в свою очередь содержат выбранные для прохождения вопросы и их порядок.

2022-05-15 17:52 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>    private final QuestionService questionService;
Не поняла что нужно удалить.

2022-05-15 17:59 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
> +  public Set<TestPassQuestion> getUnfinishedPassQuestions(Integer userId) {
ok

2022-05-15 17:59 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
>    @Transactional(readOnly = true)
ok

2022-05-15 19:13 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionDto.java
> +    if (q == null) {
ok

2022-05-15 19:23 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +        .createQuery("select tp from TestPass tp join fetch tp.questions where tp.userId = :user_id and tp.timeFinished is null ", TestPass.class)
ok

2022-05-15 20:07 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestPassService.java
>    private final QuestionService questionService;
12 строку

2022-05-16 19:20 UTC, Diacrome requested changes
нормально.
чуть по комментам и следить за релизом метода получения userId
его внедрить и ок.

2022-05-16 19:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +        .setParameter("test_id", testId).list().isEmpty();
странно.
можно сет макс резалт 1
и uniqeresult != null
или через дженерик  get != null

2022-05-16 19:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +        .setParameter("user_id", userId).getResultStream().collect(Collectors.toSet());
нормально.
по форматированию обычно перед точкой на следующу строку переносят, как 
.setParamer
.getresult
...

2022-05-16 19:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
> +      return Response.status(400, "There is no such test in the system ").build();
не найдено 404

2022-05-17 17:54 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +        .setParameter("test_id", testId).list().isEmpty();
ok

2022-05-17 19:53 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/TestPass.java
> +  @Cascade(CascadeType.SAVE_UPDATE)
ок

2022-05-17 20:15 UTC, Diacrome requested changes
1 замечание

2022-05-17 20:15 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return allQuestions.subList(0, testService.getTestSizeById(testId));
упадет если тест сайз больше количества вопросов

2022-05-18 14:43 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return allQuestions.subList(0, testService.getTestSizeById(testId));
добавила проверку

2022-05-18 14:44 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
> +      return Response.status(400, "There is no such test in the system ").build();
ok

2022-05-18 18:23 UTC, Diacrome approved these changes
ошибка должна быть однозанчной
ок пока

2022-05-18 18:23 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestPassResource.java
> +    return Response.status(400, "Failure: this user has already started the test or not enough questions for the test")
ага пляши гадай что там творится. так не делается.

2022-05-19 01:01 UTC, merged