SS-34 Added counting of test result
Diacrome/super-scoring pull request #33
Opened 2022-05-18 13:20 UTC by newvasuki-newvasuki

https://trello.com/c/hDH5hhbn/43-ss-34-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-testpass-%D1%80%D0%B5%D0%B7%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D1%82-%D1%82%D0%B5%D1%81%D1%82%D0%B0  SS-34 Added counting of test result

2022-05-19 20:17 UTC, Diacrome requested changes
по замечаниям

2022-05-19 20:17 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    if (testDao.getTestQuantity(testPassDao.getTestIdByUserId(userId)) == (questionOrder + 1)) {
так не пойдет.
нужно проверять есть ли хоть 1 неотвеченный вопрос в тесте

2022-05-19 20:17 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      if(questionDao.getTrueAnswerOnQuestion(testPass.getQuestionIds().get(index))
слишком много запросов в базу
нужно за 1 запрос получить вопросы (а лучше список вопросов получить в предыдущем методе)
за  другой вопрос все ответы
все покащеварить на уровне приложения
и записать результаты

2022-05-19 20:17 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    TestPass testPass = testPassDao.get(TestPass.class,testPassId);
форматирование

2022-05-20 04:52 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    if (testDao.getTestQuantity(testPassDao.getTestIdByUserId(userId)) == (questionOrder + 1)) {
А что если пользователь ничего не выбрал и у него время на вопрос истекло?

2022-05-20 05:05 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    if (testDao.getTestQuantity(testPassDao.getTestIdByUserId(userId)) == (questionOrder + 1)) {
ок

2022-05-20 05:05 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      if(questionDao.getTrueAnswerOnQuestion(testPass.getQuestionIds().get(index))
ок

2022-05-20 05:05 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    TestPass testPass = testPassDao.get(TestPass.class,testPassId);
ок

2022-05-21 21:06 UTC, Diacrome requested changes
см замечания

2022-05-21 21:06 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      if (listQuestionByTestPass.stream()
очень долго гонять каждый раз поиск. оптимизировать

2022-05-21 21:06 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +import javax.ws.rs.QueryParam;
это чего?

2022-05-21 21:14 UTC, Diacrome commented on backend/init.sql
> +    value_true_answer smallint
если  2е закоммитились можно не менять

2022-05-22 10:07 UTC, newvasuki-newvasuki commented on backend/init.sql
> +    value_true_answer smallint
я тогда сделаю как у Марии да и дело с концом

2022-05-22 10:08 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    if (testDao.getTestQuantity(testPassDao.getTestIdByUserId(userId)) == listAnswerByTestPass.size()) {
в 24 getTestPassIdByUserId совсем другой метод

2022-05-22 10:10 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
>    public void saveAnswer(Integer userId, Integer questionOrder, String answerText) {
свое я сделаю в одной транзакции, а saveAnswer не мой метод, но его тоже сделаю в одной транзакции

2022-05-22 10:10 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      if (listQuestionByTestPass.stream()
ок

2022-05-22 10:11 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/AnswerResource.java
> +import javax.ws.rs.QueryParam;
тестировал свой код, завал параметры через строку в браузере, а не через форму, формы то нет, вот и осталось

2022-05-23 16:06 UTC, Diacrome requested changes
весь метод saveAnswer делать в 1 транзакции.
иначе если у нас электричество отключат на полпути, мы никогда тест не завершим, даже если все вопросы отвечены

2022-05-23 16:08 UTC, Diacrome commented
еще на мастер прребейзить

2022-05-23 16:32 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +    String query = "UPDATE test_pass SET final_score = (SELECT COUNT (DISTINCT question.id) " +
ок

2022-05-23 16:41 UTC, newvasuki-newvasuki commented on backend/init.sql
> +    answer           text    not null,
json нет смысла делать, всё равно в приложении он идёт как String, он только мешается, при сравнении String с json возникает ошибка

2022-05-23 16:42 UTC, newvasuki-newvasuki commented on backend/init.sql
> +    answer           text    not null,
кроме, как здесь, answer json нигде не используется, на фронт правильный ответ не посылаем

2022-05-25 17:50 UTC, Diacrome requested changes
по вопросам

2022-05-25 17:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  public ArrayList<Answer> getListAnswerByTestPassId(Integer testPassId) {
```suggestion
  public List<Answer> getListAnswerByTestPassId(Integer testPassId) {
```

2022-05-25 17:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    ArrayList<Answer> arrayAnswerByTestPass = answerDao.getListAnswerByTestPassId(testPassId);
```suggestion
    List<Answer> arrayAnswerByTestPass = answerDao.getListAnswerByTestPassId(testPassId);
```

2022-05-25 17:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +  public void checkAndSetResultForTestPass(Integer testPassId) {
зачем public?

2022-05-25 17:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  @Transactional(readOnly = true)
зачем транзакция если она используется только под другой транзакцией?

2022-05-25 17:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +  @Transactional(readOnly = true)
зачем транзакция если она используется только под другой транзакцией?

2022-05-25 17:50 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +  @Transactional(readOnly = true)
зачем транзакция если она используется только под другой транзакцией?

2022-05-26 08:59 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +  public void checkAndSetResultForTestPass(Integer testPassId) {
ок

2022-05-26 09:01 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  @Transactional(readOnly = true)
на случай, если метод будет вызван из какого-то другого места, по умолчанию вложенные транзакции присоединяются к объединяющей, мне представляется больше смысла поставить @Transactional

2022-05-26 09:02 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +  @Transactional(readOnly = true)
на случай, если метод будет вызван из какого-то другого места, по умолчанию вложенные транзакции присоединяются к объединяющей, мне представляется больше смысла поставить @transactional

2022-05-26 09:02 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +  @Transactional(readOnly = true)
на случай, если метод будет вызван из какого-то другого места, по умолчанию вложенные транзакции присоединяются к объединяющей, мне представляется больше смысла поставить @transactional

2022-05-26 09:12 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    ArrayList<Answer> arrayAnswerByTestPass = answerDao.getListAnswerByTestPassId(testPassId);
в checkAndSetResultForTestPass я считаю лучше явно прописать ArrayList, чтобы тот кто будет работать с кодом после меня явно видел, что в этом методе необходимо использовать ArrayList, а не LinkedList, чтобы ассимптота метода оставалась O(n), а не O(n^2),  а если ему это будет не важно, то он сам поменяет, поэтому для совместимости возвращаемого значения в getListAnswerByTestPassId также пишу ArrayList

2022-05-26 09:13 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  public ArrayList<Answer> getListAnswerByTestPassId(Integer testPassId) {
в checkAndSetResultForTestPass я считаю лучше явно прописать ArrayList, чтобы тот кто будет работать с кодом после меня явно видел, что в этом методе необходимо использовать ArrayList, а не LinkedList, чтобы ассимптота метода оставалась O(n), а не O(n^2),  а если ему это будет не важно, то он сам поменяет, поэтому для совместимости возвращаемого значения в getListAnswerByTestPassId также пишу ArrayList

2022-05-26 15:02 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +  @Transactional(readOnly = true)
кому надо тот сделает.
убрать

2022-05-26 15:03 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    ArrayList<Answer> arrayAnswerByTestPass = answerDao.getListAnswerByTestPassId(testPassId);
это не так работает.
если везде поставить List при компилятор сам будет каждый раз выбирать что удобнее и оптимизировать код

2022-05-27 15:32 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +  @Transactional(readOnly = true)
кому надо тот сделает.
убрать

2022-05-27 15:32 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/AnswerDao.java
> +  @Transactional(readOnly = true)
кому надо тот сделает.
убрать

2022-05-27 15:33 UTC, Diacrome approved these changes

2022-05-27 15:53 UTC, merged