SS-37 Test adding
Diacrome/super-scoring pull request #36
Opened 2022-05-20 02:35 UTC by Lilongue

Карточка trello:
https://trello.com/c/gPzN07xc/45-ss-37-%D1%83%D1%80%D0%BB-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D0%B0

2022-05-21 20:40 UTC, Diacrome requested changes
Проверить работоспособность потом посылать на ревью

2022-05-21 20:40 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +    //return true;
убрать

2022-05-21 20:40 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  @Transactional(readOnly = true)
точно не сохранит потому что транзакция только для чтения

2022-05-21 20:40 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  @Transactional(readOnly = true)
точно не сохранит потому что транзакция только для чтения

2022-05-22 08:32 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +    //return true;
Убрал

2022-05-22 08:36 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  @Transactional(readOnly = true)
Согласен, что так не надо и убрал readOnly, но точно сохранялось (есть видосик с прувом). Почему сработал неправильный вариант - объяснить не могу.

2022-05-22 08:36 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +  @Transactional(readOnly = true)
Согласен, что так не надо и убрал readOnly, но точно сохранялось (есть видосик с прувом). Почему сработал неправильный вариант - объяснить не могу.

2022-05-22 08:38 UTC, Lilongue commented
Дополнительно:
- изменил способ получения id только что записанного теста.
- добавил инфу в readme (а то опять забуду)

2022-05-23 14:52 UTC, Diacrome approved these changes
прибраться и ок

2022-05-23 14:52 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +  public Integer getMaxId() {
это где используется?

2022-05-23 14:52 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    Integer savedId = -1;
```suggestion
    Integer savedId;
```

2022-05-24 04:48 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/AuthService.java
> +    //return true;
Ok

2022-05-24 04:49 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/dao/TestDao.java
> +  public Integer getMaxId() {
Прощу прощения за невнимательность - осталось от предыдущего метода получения Id. Убираю.

2022-05-24 05:39 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    Integer savedId = -1;
Ok

2022-05-24 05:44 UTC, merged