SS-36 Add question adding
Diacrome/super-scoring pull request #40
Opened 2022-05-22 22:12 UTC by moonb3rry

https://trello.com/c/9ffD68mC

2022-05-23 15:41 UTC, Diacrome requested changes
дополнительно исправить транзации на чтение в backend/src/main/java/ru/hh/superscoring/service/AuthService.java
можно тут можно отдельной задачей, на создание сущностьей не должно быть readonly true

2022-05-23 15:41 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    } catch (NoResultException e) {
uniqueresult такую ошибку не кидает
ее кидает getsingleresult

2022-05-23 15:41 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  @Transactional(readOnly = true)
как это оно пишет в базу если транзация readonly?

2022-05-25 18:33 UTC, Diacrome requested changes
см. вопросы

2022-05-25 18:33 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @Produces("application/json")
эт зачем?

2022-05-25 18:33 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    Boolean questionAdded;
а это зачем?

2022-05-25 18:33 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    questionAdded = questionService.addQuestion(question);
сначала на админа проверяем, может это делать и не придется

2022-05-25 18:33 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return true;
вопрос добавляем, а сохранить забываем

2022-05-27 13:49 UTC, moonb3rry commented on backend/README.md
> +- 200 и "Question added", если вопрос успешно добавлен
ок

2022-05-27 13:49 UTC, moonb3rry commented on backend/README.md
> +- 404 и "Access denied", если пользователь не является админом
ок

2022-05-27 13:50 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return true;
действительно... исправила

2022-05-27 13:51 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +  @Produces("application/json")
убрала

2022-05-27 13:51 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    Boolean questionAdded;
переделаю логику

2022-05-27 13:51 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    questionAdded = questionService.addQuestion(question);
ок

2022-05-27 21:02 UTC, Diacrome requested changes
ребейз на мастер

2022-05-29 17:02 UTC, Diacrome approved these changes

2022-05-29 18:23 UTC, merged