SS-39 Added the ability to set the inactive status for a question
Diacrome/super-scoring pull request #41
Opened 2022-05-23 12:54 UTC by newvasuki-newvasuki

https://trello.com/c/KsucpqD7/48-ss-39-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%B8%D0%B7-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80%D0%B0-%D1%82%D0%B5%D1%81%D1%82%D0%B0 SS-39 Added the ability to set the inactive status for a question

2022-05-23 16:15 UTC, Diacrome requested changes
см вопросы.

2022-05-23 16:15 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Question.java
> +  @Column(name = "activity")
activity это немного не так переводится
active

2022-05-23 16:15 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +  public Response disableActivityQuestion(@QueryParam("questionId") int questionId,
не вижу QueryParam в url

2022-05-23 16:15 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +  @Consumes({MediaType.TEXT_HTML})
зачем на чтото принимать?

2022-05-23 16:15 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +      return Response.status(404, "Role user is not ADMIN. Access denied!").build();
403

2022-05-23 16:15 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public void setQuestionNotActivity(Integer questionId) {
в транзакции надо делать. а то вдруг в момент между проверкой и записью вопрос удалят

2022-05-23 17:03 UTC, newvasuki-newvasuki commented on backend/init.sql
> +    answer           text    not null,
хибер поднимает  объект вопроса из базы, превращает json в String, а обратно update уже не может сделать, в обратную сторону String и json не совместимы, кидает ошибку

2022-05-23 17:04 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/entity/Question.java
> +  @Column(name = "activity")
ок

2022-05-23 17:04 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +  public Response disableActivityQuestion(@QueryParam("questionId") int questionId,
ок

2022-05-23 17:05 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +  @Consumes({MediaType.TEXT_HTML})
ок

2022-05-23 17:05 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +      return Response.status(404, "Role user is not ADMIN. Access denied!").build();
ок

2022-05-25 18:03 UTC, Diacrome approved these changes
пожалуйста, отвечай на все комментарии
чтобы добавить красивую ссылку на карточку трело, нужно на карточке нажать кнопку полделиться

2022-05-25 18:27 UTC, merged

2022-05-25 18:31 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/resource/QuestionResource.java
> +    Response response = checkAuthorization(authorizationToken);
не понял комментария