SS-40
Diacrome/super-scoring pull request #42
Opened 2022-05-25 04:14 UTC by Lilongue

Карточка Trello:
https://trello.com/c/awtxBgqJ/49-ss-40-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%B0
Кроме выключения сделал включение теста отдельной ручкой.
Изменения затронули: создание теста (по умолчанию создается активным),информацию о тесте и запуск теста (создание прохождения).
Не вполне ясно, что делать, если тест отключен, скажем, во время тестирования кем-то. Нужно ли добавлять проверку на включенность теста?

2022-05-26 14:37 UTC, Diacrome requested changes
по вопросам

2022-05-26 14:37 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    if (!testService.isTestActive(id)) {
зачем 2 похода в базу хотя можно сразу получить тест и у него проверить активен ли он

2022-05-26 14:37 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +                                 @HeaderParam("authorization") String authorizationToken){
форматирование

2022-05-27 15:55 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    if (!testService.isTestActive(id)) {
Может, тогда перенести проверку активности в сервис, в функцию получения теста по id? И возвращать null при неактивном тесте. Тогда в ресурсе ситуации отсутствия теста и его неактивности будут идентичны/неразличимы.

2022-05-27 15:56 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +                                 @HeaderParam("authorization") String authorizationToken){
Исправлю.

2022-05-27 17:24 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/resource/TestResource.java
> +    if (!testService.isTestActive(id)) {
Оптимизировал тут и в прохождении, объединив 2 похода в базу в 1

2022-05-27 21:01 UTC, Diacrome approved these changes
короткую ссылку на карточку трело можно получить, нажав поделиться

2022-05-27 21:03 UTC, Diacrome commented
Поправить описание ПР

2022-05-29 07:11 UTC, merged