SS-41 added test requests for testing the backend API
Diacrome/super-scoring pull request #46
Opened 2022-05-29 10:14 UTC by newvasuki-newvasuki

https://trello.com/c/hh0dHWdH

2022-05-29 17:01 UTC, Diacrome requested changes
необходимо запускать авто-тесты при старте приложения.

по возможности запускать толькое если передан ключ.

суть не в 1 тесте а в инфраструктуре

2022-05-30 17:27 UTC, newvasuki-newvasuki commented
ок

2022-05-31 20:20 UTC, Diacrome commented on tests/tests.json
> +							"raw": "{{server}}{{beginTestEndPoint}}/info/100500",
лучше 0 поставить

2022-06-01 08:51 UTC, newvasuki-newvasuki commented
Создал два ПР для удаления двух файлов restart_with_new_base

2022-06-01 11:08 UTC, newvasuki-newvasuki commented on docker-compose.yml
> +    entrypoint: sh wait-for.sh backend:8000 --timeout=1000 -- newman run tests.json
я попробовал варианты с depends_on: там проверка на здоровье идёт до запуска backend, в результате оказывается, что backend не здоров, чтобы эту проблему решить, народ отдельные проекты на java пишет, что по трудозатратам бессмысленно, поскольку уже есть рабочий вариант

2022-06-01 20:09 UTC, Diacrome commented on docker-compose.yml
> +    entrypoint: sh wait-for.sh backend:8000 --timeout=1000 -- newman run tests.json
ok

2022-06-02 06:42 UTC, newvasuki-newvasuki commented
ок

2022-06-02 19:36 UTC, Diacrome approved these changes
перенести ссылки в бэкенд редми

2022-06-02 19:36 UTC, Diacrome commented on tests/Большой гайд по тестированию с Postman для начинающих.url
> +URL=https://testengineer.ru/gajd-po-testirovaniyu-v-postman/
что это за файлы?
как их использовать?
просто в backend/readme.md добавить, да и все.

2022-06-03 05:55 UTC, newvasuki-newvasuki commented on tests/Большой гайд по тестированию с Postman для начинающих.url
> +URL=https://testengineer.ru/gajd-po-testirovaniyu-v-postman/
ок

2022-06-03 15:58 UTC, merged