SS-33 Added answer verification
Diacrome/super-scoring pull request #47
Opened 2022-05-29 18:08 UTC by bagmarya

2022-05-30 20:12 UTC, Diacrome requested changes
по вопросам

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    String payload = questionDao.getPayloadByQuestionId(questionId);
зачем 4 раза в базу бегать за 1 значением, когда можно всего 1 ?

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    }
можно все унести в классс валидатора

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    }
можно все унести в валидатор

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +      if (fieldNames.next() == "answer"
ну нельзя так стринги сравнивать

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +      if (fieldNames.next() == "answer"
ну нельзя так стринги сравнивать

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +        return true;
можно сразу без ифа возвращать результат цепочки условий

2022-05-30 20:12 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +        return true;
можно сразу без ифа возвращать результат цепочки условий

2022-05-31 14:40 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +    }
ok

2022-06-01 17:23 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +}
ok

2022-06-01 17:23 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +  private final QuestionDao questionDao;
убрала

2022-06-01 17:23 UTC, bagmarya commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +  public Integer getQuestionIdByQuestionIdOrder(Integer testPassId, Integer questionIdOrder) {
убрала

2022-06-01 20:07 UTC, Diacrome approved these changes

2022-06-02 18:04 UTC, merged