SS-43: all-tests all-questions-for-test all-questions added
Diacrome/super-scoring pull request #51
Opened 2022-06-02 16:35 UTC by nicepeopleproject

https://trello.com/c/hKI0Po6h

2022-06-02 19:40 UTC, Diacrome requested changes
договаривались сделать с пагинацией.
Спроси у Марии, он уже делала

2022-06-05 18:35 UTC, Diacrome requested changes
название комитов не по правилам - будешь мерджить - добавь имя ветки
а так по вопросам

2022-06-05 18:35 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
по умолчанию в сервисе вешаем транзакции

2022-06-05 18:35 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
по умолчанию в сервисе вешаем транзакции

2022-06-05 18:35 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionBoardDto.java
> +  public static QuestionBoardDto map(List<Question> questions, int page, int perPage) throws JsonProcessingException {
где у нас возможно JsonProcessingException ?

2022-06-05 18:35 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionBoardDto.java
> +    Integer offset = page * perPage + 1;
```suggestion
    int offset = page * perPage + 1;
```

2022-06-05 18:35 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dto/TestBoardDto.java
> +  public static TestBoardDto map(List<Test> tests, int page, int perPage) throws JsonProcessingException {
не кидает ошибку

2022-06-08 14:49 UTC, nicepeopleproject commented
> договаривались сделать с пагинацией. Спроси у Марии, он уже делала

ок

2022-06-08 14:55 UTC, nicepeopleproject commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
ок

2022-06-08 14:55 UTC, nicepeopleproject commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
ок

2022-06-08 14:56 UTC, nicepeopleproject commented on backend/src/main/java/ru/hh/superscoring/dto/QuestionBoardDto.java
> +    Integer offset = page * perPage + 1;
исправил

2022-06-08 14:56 UTC, nicepeopleproject commented on backend/src/main/java/ru/hh/superscoring/dto/TestBoardDto.java
> +  public static TestBoardDto map(List<Test> tests, int page, int perPage) throws JsonProcessingException {
ок

2022-06-08 19:54 UTC, Diacrome requested changes
по замечания + ребейз на мастер

2022-06-08 19:54 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
а тут чего не удалил?

2022-06-08 19:54 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
удалить

2022-06-14 14:20 UTC, nicepeopleproject commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  @Transactional(readOnly = true)
Сделал

2022-06-14 14:54 UTC, Diacrome requested changes
решить конфликты с мастером

2022-06-15 22:23 UTC, Diacrome approved these changes

2022-06-16 08:25 UTC, merged