Ss 57
Diacrome/super-scoring pull request #52
Opened 2022-06-04 11:48 UTC by newvasuki-newvasuki

https://trello.com/c/Dcvi3z3M

2022-06-05 19:01 UTC, Diacrome requested changes
хорошая работа, небольшие правки

2022-06-05 19:01 UTC, Diacrome commented on backend/README.md
> +- 400 и "*****" описание кода ошибки системы Hibernate
инфо о наших внутренностях отдавать не очень хорошо

2022-06-05 19:02 UTC, newvasuki-newvasuki commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    for (int i = 1; i <= testDao.getTestSizeByTestPassId(testPassId); i++) {
ок

2022-06-05 19:03 UTC, newvasuki-newvasuki commented on backend/README.md
> +- 400 и "*****" описание кода ошибки системы Hibernate
так там уже подобное в 3-4 местах, везде удалить?

2022-06-06 21:34 UTC, Diacrome approved these changes
по мелочи поправить

2022-06-06 21:34 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/StatusService.java
> +    final Integer NUMBER_OF_QUESTIONS = testDao.getTestSizeByTestPassId(testPassId);
большими буквами глобальные константы только делаем

2022-06-06 21:34 UTC, Diacrome commented on backend/README.md
> +- 400 и "*****" описание кода ошибки системы Hibernate
сейчас не надо
заведи задачу на рефакторинг и укажи места
делать самому не обязательно

2022-06-07 05:57 UTC, merged