SS-47 Added unit tests for JsonValidator
Diacrome/super-scoring pull request #57
Opened 2022-06-08 18:26 UTC by bagmarya

https://trello.com/c/NfDYvp72

2022-06-08 19:50 UTC, Diacrome requested changes
использовать циклы и коллекции

2022-06-08 19:50 UTC, Diacrome commented on backend/src/test/java/JsonValidatorTest.java
> +    String goodJson2 = "{\"multiple_answer1\": \"2\"}";
в коллекцию

2022-06-08 19:50 UTC, Diacrome commented on backend/src/test/java/JsonValidatorTest.java
> +    String badJson5 = "{\"multiple_answer1 \"2\", \"multiple_answer2\": \"4\"}";
в коллекцию

2022-06-08 19:50 UTC, Diacrome commented on backend/src/test/java/JsonValidatorTest.java
> +    assertTrue(JsonValidator.verifyMultipleChoice(goodJson2, questionPayload));
цикл

2022-06-08 19:50 UTC, Diacrome commented on backend/src/test/java/JsonValidatorTest.java
> +        JsonValidator.verifyMultipleChoice(badJson5, questionPayload));
цикл, можно без спец комметариев.

2022-06-09 17:23 UTC, bagmarya commented on backend/src/test/java/JsonValidatorTest.java
> +    String goodJson2 = "{\"multiple_answer1\": \"2\"}";
ok

2022-06-09 17:23 UTC, bagmarya commented on backend/src/test/java/JsonValidatorTest.java
> +    String badJson5 = "{\"multiple_answer1 \"2\", \"multiple_answer2\": \"4\"}";
ok

2022-06-09 17:24 UTC, bagmarya commented on backend/src/test/java/JsonValidatorTest.java
> +    assertTrue(JsonValidator.verifyMultipleChoice(goodJson2, questionPayload));
ok

2022-06-09 17:24 UTC, bagmarya commented on backend/src/test/java/JsonValidatorTest.java
> +        JsonValidator.verifyMultipleChoice(badJson5, questionPayload));
ok

2022-06-09 22:26 UTC, Diacrome requested changes

2022-06-09 22:26 UTC, Diacrome commented on backend/src/test/java/JsonValidatorTest.java
> +    String questionPayload = "{\"1\": 1, \"2\": 3, \"3\": 4, \"4\": 6}";
переиспользуемые переменные в констаны класса

2022-06-09 22:26 UTC, Diacrome commented on backend/src/test/java/JsonValidatorTest.java
> +    List<String> badJsons = List.of(
разбить на 2 разных теста
позитивный
негативный

2022-06-10 15:36 UTC, bagmarya commented on backend/src/test/java/JsonValidatorTest.java
> +    String questionPayload = "{\"1\": 1, \"2\": 3, \"3\": 4, \"4\": 6}";
ok

2022-06-10 15:36 UTC, bagmarya commented on backend/src/test/java/JsonValidatorTest.java
> +    List<String> badJsons = List.of(
ok

2022-06-11 20:06 UTC, Diacrome approved these changes

2022-06-12 09:48 UTC, merged