SS-51 Payload validation in question adding
Diacrome/super-scoring pull request #66
Opened 2022-06-14 00:54 UTC by Lilongue

Карточка trello:
https://trello.com/c/vPIystr7

2022-06-16 18:36 UTC, Diacrome requested changes

2022-06-16 18:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +    if (answerType == QuestionAnswerType.SINGLE_CHOICE || answerType == QuestionAnswerType.MULTIPLE_CHOICE) {
что за условие? почему или?

2022-06-16 18:36 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    if (!JsonValidator.verifyPayload(newQuestion.getPayload(), newQuestion.getAnswerType())) {
лучше единообразно делать с точки зрения ловли ошибки, или всегда снаружи, либо всегда внутри.

неплохо бы еще пользователю возвращать ошибку с указаним поля где упало

2022-06-17 15:47 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +    if (answerType == QuestionAnswerType.SINGLE_CHOICE || answerType == QuestionAnswerType.MULTIPLE_CHOICE) {
Оказалось, что вид payload`а для этих двух типов вопросов одинаков. Отличаются только правильные ответы, которые валидируются отдельно.

2022-06-17 15:52 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    if (!JsonValidator.verifyPayload(newQuestion.getPayload(), newQuestion.getAnswerType())) {
Ок. Согласен: сделаю одинаково обработку ошибок и на фронт проброшу сообщение о том какое поле не прошло валидацию.

2022-06-21 15:20 UTC, Diacrome approved these changes
С учётом вопросов

2022-06-21 15:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public Boolean addQuestion(Question newQuestion) throws IllegalArgumentException{
Простой boolean

2022-06-21 15:20 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +    if (answerType == QuestionAnswerType.MULTIPLE_QUESTIONS_SINGLE_CHOICE) {
Что за моструозный тип ответа?
Правда есть такой? Пояни с примером

2022-06-21 18:04 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/util/JsonValidator.java
> +    if (answerType == QuestionAnswerType.MULTIPLE_QUESTIONS_SINGLE_CHOICE) {
Да. Это у нас так назвали тип вопроса в enum. Это вопросы в которых есть несколько пропусков в каждом из которых варианты ответа с единственным выбором. По поводу названия - хм. Выглядит действительно страшновато, может FILL_GAPS было бы короче, но я пользовался тем что было

2022-06-21 18:04 UTC, Lilongue commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public Boolean addQuestion(Question newQuestion) throws IllegalArgumentException{
Ок. Заменю.

2022-06-23 09:20 UTC, Diacrome approved these changes

2022-06-24 13:54 UTC, merged