SS-67 Add test creating with distribution rules
Diacrome/super-scoring pull request #69
Opened 2022-06-18 14:54 UTC by moonb3rry

https://trello.com/c/q77O4MuK

Алгоритм:
1. Составляю List с распределениями {вес, кол-во вопросов} для нужного теста, и для каждого распределения:
1.1. Выбираю все вопросы из теста с выбранным весом
1.2. Перемешиваю, получаю список
1.3. Выбираю нужное количество из этого списка и добавляю это в итоговый список

Добавить пагирование (?)

2022-06-18 16:39 UTC, Diacrome reviewed
Ответить на вопросы

2022-06-18 16:39 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return questions;
А сохраняются вопросы подобраные вопросы для теста?

2022-06-18 16:39 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public List<Question> getQuestionsForTestByDistribution(Integer testId) {
Не вижу использования метода. Я с телефона,  ты его уже используешь?

2022-06-18 16:56 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public List<Question> getQuestionsForTestByDistribution(Integer testId) {
Пока нигде. Вчера на стендапе сказали без ручки делать, просто чтобы была возможность получить

2022-06-18 16:59 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return questions;
Нет. Это получается в TestPassService еще один метод добавить или переписать еще строчку в существующем методе (старт теста), но ломать уже работающее не хочется

2022-06-18 17:04 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public List<Question> getQuestionsForTestByDistribution(Integer testId) {
Да, в рамках этой задачи

2022-06-18 17:04 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return questions;
А надо

2022-06-18 17:05 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +  public List<Question> getQuestionsForTestByDistribution(Integer testId) {
Ок

2022-06-18 17:06 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return questions;
Да простят меня коллеги

2022-06-18 19:23 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return questions;
Поясни,ты что то ломаешь?

2022-06-18 19:25 UTC, Diacrome requested changes
Надо уменьшить число походов в базу.
Лучше брать все вопросы за раз, а в джаве кашеварить распределять

2022-06-18 19:26 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +    return questions;
Нет, просто в сервисе один метод набора вопросов заменила новым, проверила, работает

2022-06-21 13:37 UTC, Diacrome approved these changes
См замечание

2022-06-21 14:16 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/QuestionDao.java
> +  public List<Question> getQuestionsByWeightForTest(Integer testId, Integer questionWeight) {
ок

2022-06-21 15:32 UTC, Diacrome requested changes
См комент

2022-06-21 15:32 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +      for (Question question : questions) {
Очень долго и зависит от количества вопросов. 
Переписать на набор случайных вопросов из листа по индексу.
Если нет идей как быстро сделать- спроси я подскажу.
Естественно вопросы не должны повторяться.

2022-06-21 21:58 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/QuestionService.java
> +      for (Question question : questions) {
ок

2022-06-22 13:05 UTC, Diacrome approved these changes
Завести задачу на оптимизацию случайного выбора вопросов

2022-06-22 15:17 UTC, merged