SS-78 Add timeout check in test pass
Diacrome/super-scoring pull request #84
Opened 2022-06-25 15:18 UTC by moonb3rry

https://trello.com/c/JZ633iIS

2022-06-26 11:28 UTC, Diacrome requested changes
По вопросам

2022-06-26 11:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/entity/Test.java
> +  private long timeLimit;
Почему колонка в sql small int а тут long?

2022-06-26 11:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +        .createQuery("update TestPass tp SET tp.status = 'TIMEOUT' where id = :id")
Использовать enum

2022-06-26 11:28 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw new TimeoutException("Test pass time limit exceeded!");
Это ошибка бизнес логики, а тут кидает java ошибку, которая для спец ситуации создана
Сделать свою ошибку и чтоб она возвращала код 400

2022-06-26 11:37 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/entity/Test.java
> +  private long timeLimit;
Изначально был short, для LocalDateTime сделала long, исправлю в бд

2022-06-26 11:37 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/dao/TestPassDao.java
> +        .createQuery("update TestPass tp SET tp.status = 'TIMEOUT' where id = :id")
Ок

2022-06-26 11:38 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/AnswerService.java
> +      throw new TimeoutException("Test pass time limit exceeded!");
Ок

2022-06-28 06:45 UTC, Diacrome approved these changes

2022-06-28 11:04 UTC, merged