SS-100 Add question distribution url, validate distribution on test a…
Diacrome/super-scoring pull request #99
Opened 2022-07-04 12:36 UTC by moonb3rry

…ctivation

https://trello.com/c/REIEBnVQ

2022-07-06 07:45 UTC, Diacrome requested changes
см вопросы

2022-07-06 07:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +    if (testDao.get(Test.class, testId).getQuestionQuantity() == questionDistributionDao.getQuestionCountForTest(testId)) {
такой проверки недостаточно .
она просто проверяет общее количество вопросов? 
нужно проверрять есть ли достаточно вопросов каждого типа, если я правильно понял. если не правильно, поясни

2022-07-06 07:45 UTC, Diacrome commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +    } else {
если есть такая дистрибюция - кидать ошибку а не править

2022-07-06 11:44 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +    } else {
ок

2022-07-06 11:45 UTC, moonb3rry commented on backend/src/main/java/ru/hh/superscoring/service/TestService.java
> +    if (testDao.get(Test.class, testId).getQuestionQuantity() == questionDistributionDao.getQuestionCountForTest(testId)) {
ты правильно понял, надо действительно проверять есть ли нужное кол-во вопросов каждого веса, исправлю

2022-07-08 17:55 UTC, Diacrome approved these changes
Обязательно проверить работоспособность

2022-07-08 21:49 UTC, merged